### ISSUE TITLE
erreur stage 1 code retour 0

### ISSUE THREAD

**Issue by squal95** [yoan-m/jeedom_gsl#15]
Bonjour,

ce plugin est vraiment génial et j'entrevois déja les possibilités de scénario en fonction de ma géoloc

cependant pour le moment je rencontre beaucoup de probleme avec un "erreur stage 1 code retour0"

j'ai reussi à obtenir de nouvelles infos de localisation en supprimant le plugins et redémarrant jeedom mais le plugins replante au bout de quelques heures.

j'ai bien autoriser les applications moins sécurisé aupres de google sécurité et bien reconnu l'activité détécté comme suspect mais rien ni fait ca ne marche toujours pas

auriez vous une idée pour résoudre ce probleme?

merci par avance

**Comment by yoan-m** [comment]
Bonjour,

Il s'agit d'une limitation de google sur les requêtes trop récurrentes.
Après un certain nombres de requêtes trop rapprochées, un capcha est affiché et malheureusement le plugin ne peut pas le résoudre.

Afin d'éviter ce soucis il faut baisser la fréquence de rafraîchissement (Je suis à 15min dans ma config) */15 * * * *

Yoan.

**Comment by squal95** [comment]
Bonsoir Yoann,
J'ai donc passé le plugin à 15 min comme conseillé après avoir tout réinitialisé, cela à fonctionné...de 16h à 19h40
j'ai donc supprimé le plugin une nouvelle fois, redémarré jeedom et suis passé à 20min de rafraîchissement et cela à de nouveau fonctionné... de 13h à 19h45 et depuis toujours le même message d'erreur "code retour 0"
j'avoue que je n'arrive pas à comprendre pourquoi cela fonctionne et que tout s’arrête d'un coup (bizarrement avant 20h)
j'ai essayé ensuite de supprimer le plugin et le réinstaller sans redémarrer jeedom et même message erreur
j'ai donc (a l'instant) de nouveau supprimé, redémarré jeedom, réinstallé le plugin et tout re paramétré avec 15min de rafraichissement et cela re fonctionne à nouveau
Je ne pense donc pas que google soit en cause car aucune alerte de sécurité, aucun mail et juste le reparametrage et redémarrage de jeedom suffit à résoudre le problème
maintenant si cette solution pouvait etre opéarationnelle sans toute ces manips ca serait mieux car jeedom gére bcp trop de choses chez moi pour me permettre de l'eteindre quotidiennement

[gsl (1).txt](https://github.com/yoan-m/jeedom_gsl/files/2713575/gsl.1.txt)

**Comment by squal95** [comment]
Bonjour Yoann,
Comme prévisible le plugin à fonctionné que quelques heures, j'ai redémarré jeedom et ca s'est remis en fonctionnement pour de nouveau quelques heures.
[gsl (2).txt](https://github.com/yoan-m/jeedom_gsl/files/2716473/gsl.2.txt)
