### ISSUE TITLE
PR pour commande geoloc - type et lieu?

### ISSUE THREAD

**Issue by Bbillyben** [yoan-m/jeedom_gsl#25]
Salut yoan,

Alors pas une issue, mais je ne savait comment initier la conversation sur github....

Je voudrais proposer un PR sur ton plugin GSL pour y ajouter la possibilité d'avoir une équipement "fix" mais dont les coordonnées sont données par une commande type info venue d'ailleurs. 
L'objectif est de consolider sur une seule carte et un seul calcul de distance des items qui bougent!

Pour la mise à jour des coordonnées/distance, j'ai 2 choix  :
1. sur le pull (https://github.com/Bbillyben/jeedom_gsl/tree/geoloc_pull)
2. sur l'event sur la commande qui expose les coordonnées (https://github.com/Bbillyben/jeedom_gsl/tree/geoloc_event)

l'event permet d'être hyper réactif, mais charge un peu plus le système, tout dépend de la fréquence de mise à jour derrière.
le pull charge moins, mais on vérifie pour les equipement si les coordonnées ont été mise à jour, et en plus ça suit la mise à jour des coordonnées reçues de google.

Est ce que ça t'intéresse ? si oui lequel? sur quelle branche?

@+

**Comment by yoan-m** [comment]
Salut, merci pour ta contribution, Je préfère le pull.
Tu peux faire une PR sur la master dans un premier temps, on la passera en stable après.

Merci :)

**Comment by Bbillyben** [comment]
Ca marche!
